Feat/map/210505sm
Nc-Nc-N/giffticon pull request #106
Opened 2021-05-09 06:43 UTC by planner26

지도로 찾는 기프티콘

-사용가이드-
*페이지 처음 로딩 시 카카오맵이 가끔 로딩이 안됩니다.. 새로고침 눌러주세요

(카테고리 클릭 -> 브랜드 클릭 -> 지도 위치 드래그하여 매장 찾기)

검색된 매장 없을 시 메세지 출력
검색된 매장 있을 시 기프티콘 출력
등록된 기프티콘 없을 시 메세지출력

등록된 브랜드의 품목마다 가장 할인률이 큰 기프티콘 출력

카카오맵 api 동기화 문제로 다중 검색 시 notFountd 메세지 출력을 거친 후 gftList가 출력됨
-> css animation으로 가려놓았습니다.

callback 동기화 문제 해결 시 animation 제거하고 리팩토링 합니다. 해결 안되면 그대로...

+상품명 한글로 16자 넘어가면 div가 깨집니다 글자크기 줄이는것도 한계가 있어서 이름을 줄여야할듯합니다.

2021-05-09 14:47 UTC, 1eehyeji approved these changes

2021-05-10 00:47 UTC, heeyoung2da requested changes

2021-05-10 00:47 UTC, heeyoung2da commented on src/main/resources/com/ncncn/mapper/GifticonMapper.xml
> +        select prod.enabled,
min(dc_prc)as dc_prc, max(dc_rate) as dc_rate 

제가 order 기능 부분에서 수정해서,, 혹시 할인율 부분 변경해주실 수 있나요?

2021-05-10 01:03 UTC, planner26 commented on src/main/resources/com/ncncn/mapper/GifticonMapper.xml
> +        select prod.enabled,
수정했습니다.

2021-05-10 01:16 UTC, heeyoung2da approved these changes

2021-05-10 06:38 UTC, chunghyeon-kim approved these changes
수고하셨습니다

2021-05-10 06:38 UTC, merged