Feat/user detail/210408ch
Nc-Nc-N/giffticon pull request #13
Opened 2021-04-11 08:59 UTC by chunghyeon-kim

상세조회페이지 기능 1차 완성(탈퇴일시 추가요망)

2021-04-12 01:05 UTC, heeyoung2da commented
강사님께서 redirect쓸 때 예외처리 해야된다고 말씀 해주셨던 게 생각나는데,, 
한 번 참고하면 좋을 거 같습니다 수고하셨습니다! ㅎ.ㅎ

2021-04-12 01:06 UTC, heeyoung2da approved these changes
강사님께서 redirect쓸 때 예외처리 해야된다고 말씀 해주셨던 게 생각나는데,,
한 번 참고하면 좋을 거 같습니다 수고하셨습니다! ㅎ.ㅎ

2021-04-12 01:22 UTC, 1eehyeji requested changes

2021-04-12 01:22 UTC, 1eehyeji commented on src/main/java/com/ncncn/service/UserCheckServiceImpl.java
>      public List<UserVO> getUserList(CriteriaCH cri) {
Exception이 발생하면 사용자가 보는 페이지는 어떻게 보여지나욥?

2021-04-12 01:22 UTC, 1eehyeji commented on src/test/java/com/ncncn/mapper/UserCheckMapperTests.java
> +    public void testUpdateMemo() {
테스트 메소드 내용 확인부탁드립니다!

2021-04-12 01:22 UTC, 1eehyeji commented on src/test/java/com/ncncn/service/UserCheckServiceTests.java
> +    public void testGetUser() {
https://in-intuition.tistory.com/10
테스트 코드 작성할 때 도움될만한 블로그 글입니다!

2021-04-13 03:18 UTC, planner26 approved these changes
고생하셨습니다!

2021-04-15 14:27 UTC, 1eehyeji approved these changes
고생많으셨습니다!

2021-04-16 00:40 UTC, merged