상품 상세 페이지(등록된 기프티콘 조회)
Nc-Nc-N/giffticon pull request #15
Opened 2021-04-12 01:14 UTC by heeyoung2da

상품 상세 페이지(구매하기)
- 상품에 등록된 기프티콘들을 가격 낮은 순으로 출력

앞으로 추가적으로 할 일
- 옵션을 선택하면 아래에 선택한 옵션 정보(기프티콘, 가격) 출력되고 구매하기 활성화
- 옵션을 선택 안 하면 구매하기 비활성화

2021-04-12 01:22 UTC, chunghyeon-kim approved these changes
수고하셨습니다!!

2021-04-12 01:30 UTC, 1eehyeji commented on src/main/webapp/WEB-INF/views/user/prod_list.jsp
> +            if(code=='' || code==null || code=='0'){
https://velog.io/@najiexx/JavaScript-%EC%99%80-%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90%EB%8F%99%EB%93%B1%EC%97%B0%EC%82%B0%EC%9E%90%EC%99%80-%EC%9D%BC%EC%B9%98%EC%97%B0%EC%82%B0%EC%9E%90
javascript에서 ==와 ===에 차이점이 있다고해서 도움될만한 글 주소 남김니다!

2021-04-12 01:31 UTC, 1eehyeji commented on src/test/java/com/ncncn/mapper/ProdMapperTests.java
> +	public void testGetGiftiList(){
https://in-intuition.tistory.com/10
테스트 코드 작성에 도움될만한 글 주소남겨욥!

2021-04-12 01:36 UTC, 1eehyeji requested changes

2021-04-12 01:36 UTC, 1eehyeji commented on src/main/java/com/ncncn/service/ProdServiceImpl.java
> +	public List<GifticonDTO> getGiftiList(String code) {
exception이 발생하는 경우 화면이 제대로 보여지나욥?

2021-04-12 01:37 UTC, heeyoung2da commented on src/test/java/com/ncncn/mapper/ProdMapperTests.java
> +	public void testGetGiftiList(){
넵 추후에 참고해보겠습니다! 감사합니당~!~!

2021-04-13 03:23 UTC, planner26 approved these changes
수고하셨어요

2021-04-14 09:27 UTC, 1eehyeji approved these changes

2021-04-14 11:37 UTC, chunghyeon-kim commented
수고하셨습니다!

2021-04-14 11:37 UTC, merged