사용자 - 마이페이지 - 구매내역 완료 (마이페이지 템플릿 수정)
Nc-Nc-N/giffticon pull request #24
Opened 2021-04-13 11:11 UTC by planner26

마이페이지 템플릿 및 구매내역 , 구매 상세 완료했습니다

2021-04-14 01:28 UTC, 1eehyeji requested changes

2021-04-14 01:28 UTC, 1eehyeji commented on src/main/java/com/ncncn/security/LoginSuccessHandler.java
> +    public UserMapper usermapper;
UserServiceImpl을 사용해서 조회하는 것도 좋을 것 같습니다!
그리고 hotfix 내용이랑 같은 내용인 것 같는데 맞나요??

2021-04-14 01:28 UTC, 1eehyeji commented on src/main/webapp/WEB-INF/views/user/mypage/deal.jsp
> +            alert("구매확정하시겠습니까?");
구매확정에 대한 간단한 안내가 들어가면 좋을 것 같아요!

2021-04-14 01:51 UTC, heeyoung2da commented on src/main/java/com/ncncn/controller/DnSController.java
> +        model.addAttribute("dealList", dealListService.getDealsWithPaging(email, cri));
userId 가져오니까 email 대신에 userId 써도 좋을 것 같아욥

2021-04-15 11:22 UTC, planner26 commented on src/main/java/com/ncncn/controller/DnSController.java
> +        model.addAttribute("dealList", dealListService.getDealsWithPaging(email, cri));
수정했습니다

2021-04-16 03:42 UTC, planner26 commented on src/main/java/com/ncncn/security/LoginSuccessHandler.java
> +    public UserMapper usermapper;
수정했습니다.

hotfix랑 같은 내용이고 현재 branch에서 급하게 필요해서 따로 수정했습니다

2021-04-16 03:42 UTC, planner26 commented on src/main/webapp/WEB-INF/views/user/mypage/deal.jsp
> +            alert("구매확정하시겠습니까?");
추가했습니다

2021-04-16 03:54 UTC, planner26 commented
> 마이페이지 템플릿 및 구매내역 , 구매 상세 완료했습니다


1. 마이페이지 템플릿 완료
   - 사이드바 링크(이후 페이지 완료시마다 추가)
   - 요약 자동 searching 트리거 (현재포인트는 어디로 링크 걸지 논의 필요)
2. 구매 내역
   - 페이지네이션, 조건별 searching
   - 모든 구매내역 출력
   - 구매확정 / 확정 완료 버튼 추가
   - 기프티콘 상세 페이지 이동 추가
3. 구매 상세
   - 보안 - 로그인한 사용자의 id값을 db와 다시 대조하여 일치 시 접근 가능 (바코드 번호가 출력되어서 추가 보안 필요)
   - 세부 구매 내역 출력
   - 구매확정 / 확정 완료 버튼 추가
   - 목록 이동 버튼
4. 판매 내역
   - 모든 등록된 기프티콘 내역 출력
   - 페이지네이션, 조건별 searching
   - 상태에 따른 판매취소 / 판매완료 버튼 출력 (거래 확정 대기 이후 판매 취소 불가)
   - 판매 상세 페이지 이동 추가
5. 판매 상세
   - 보안 - 로그인한 사용자의 id값을 db와 다시 대조하여 일치 시 접근 가능 (바코드 번호가 출력되어서 추가 보안 필요)
   - 세부 판매 내역 추가
   - 판매 취소 버튼 추가 ( 거래 확정 대기 이후 판매 취소 불가)
   - 판매 수정 버튼 추가 ( 거래 확정 대기 이후 수정 불가)
   - 수정 시 모달창 생성
   - 수정 시 비밀번호 입력, 일치 시 수정 가능

2021-04-16 04:01 UTC, chunghyeon-kim approved these changes
수고하셨습니다

2021-04-16 05:18 UTC, ByoungeunKim approved these changes
수고하셨습니다~

2021-04-16 08:26 UTC, 1eehyeji approved these changes

2021-04-16 08:27 UTC, chunghyeon-kim approved these changes
수고하셨습니다

2021-04-16 08:27 UTC, chunghyeon-kim commented
수고하셨습니다

2021-04-16 08:28 UTC, merged