콘 충전 기능 구현
Nc-Nc-N/giffticon pull request #92
Opened 2021-04-30 07:07 UTC by heeyoung2da

결제방식
: 카카오페이  -> 추후에 다른 결제 방식도 추가해볼게요!

결제 후 pnt_hist에 충전 내역 insert, user 테이블 pnt update

앞으로 진행사항
: 구매하기 기능 먼저 구현 후 콘 인출(환불), 콘 내역 조회

2021-05-01 04:08 UTC, chunghyeon-kim approved these changes
수고하셨습니다

2021-05-02 03:00 UTC, planner26 reviewed
수고하셨습니당. 등록하는 계좌는 충전 전용인가요??

2021-05-02 04:46 UTC, 1eehyeji requested changes

2021-05-02 04:46 UTC, 1eehyeji commented on src/main/resources/com/ncncn/mapper/ConMapper.xml
> +    <update id="updateUserCon">
수정할 때 up_date랑 up_user도 같이 수정해야할 것 같습니다!

수고많으셨습니다! 👍👍

2021-05-02 14:51 UTC, 1eehyeji approved these changes

2021-05-02 14:55 UTC, heeyoung2da reviewed
> 수고하셨습니당. 등록하는 계좌는 충전 전용인가요??

-> 우선 카카오페이 결제 방식은 계좌가 필요 없습니다!

2021-05-02 14:55 UTC, heeyoung2da commented on src/main/resources/com/ncncn/mapper/ConMapper.xml
> +    <update id="updateUserCon">
수정했습니다 감사합니다😊

2021-05-04 05:17 UTC, planner26 approved these changes

2021-05-05 02:29 UTC, merged